### ISSUE TITLE
Unassigned variables have default of null instead of undefined

### ISSUE THREAD

**Issue by abbondanza** [jasonwilliams/boa#113]
The following statements both print `null` instead of `undefined`.

```js
var x;
x;
```
and
```js
let x;
x;
```

Testing locally, it seems like it's enough to change the defaults at https://github.com/jasonwilliams/boa/blob/8851eba27d1df86e139e101f2b0ce26dbf3a1920/src/lib/exec.rs#L395 and https://github.com/jasonwilliams/boa/blob/8851eba27d1df86e139e101f2b0ce26dbf3a1920/src/lib/exec.rs#L407

to `ValueData::Undefined`.

**Comment by pop** [comment]
This sounds cool and I'm interested in contributing to Boa for Hacktoberfest. Mind if I start working on this?

**Comment by abbondanza** [comment]
Go for it! Should be pretty straightforward.
