### ISSUE TITLE
String.match(regexp)

### ISSUE THREAD

**Issue by jasonwilliams** [jasonwilliams/boa#114]
`match` function would need to be added to the string object here:
https://github.com/jasonwilliams/boa/blob/master/src/lib/js/string.rs

It would be very similar to:
https://github.com/jasonwilliams/boa/blob/master/src/lib/js/regexp.rs#L212-L251

Spec:
https://tc39.es/ecma262/#sec-string.prototype.match

**Comment by muskuloes** [comment]
Hi, I found this via  the hacktoberfest tag. I'll like to work on it.

**Comment by jasonwilliams** [comment]
@muskuloes ok assigned
