### ISSUE TITLE
String.matchAll(regexp)

### ISSUE THREAD

**Issue by jasonwilliams** [jasonwilliams/boa#115]
`matchAll` function would need to be added to the string object here:
https://github.com/jasonwilliams/boa/blob/master/src/lib/js/string.rs

It would be very similar to:
https://github.com/jasonwilliams/boa/blob/master/src/lib/js/regexp.rs#L212-L251

Spec:
https://tc39.es/ecma262/#sec-string.prototype.matchAll

Notes:
https://github.com/jasonwilliams/boa/blob/master/docs/debugging.md

**Comment by bojan88** [comment]
@jasonwilliams thanks for nice and straightforward issue. I'm going to start working on this one.

**Comment by jasonwilliams** [comment]
@bojan88 great, assigned!
