### ISSUE TITLE
[Easy] - increment operator is broken

### ISSUE THREAD

**Issue by jasonwilliams** [jasonwilliams/boa#118]
```js
let i = 0;
i++;
i;
```

```js
let i = 0;
++i;
i;
```

This JS generates the error:
`thread 'main' panicked at 'internal error: entered unreachable code', src/lib/exec.rs:246:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
The terminal process terminated with exit code: 101`

Issue is happening here:
https://github.com/jasonwilliams/boa/blob/master/src/lib/exec.rs#L249

Looks like more `unaryOp`s need to be added including the increment, decrement.
https://github.com/jasonwilliams/boa/blob/master/src/lib/syntax/ast/op.rs#L47-L64

Debugging:
https://github.com/jasonwilliams/boa/blob/master/docs/debugging.md

**Comment by bobbo** [comment]
I'm interested in taking a look at this for Hacktoberfest.

**Comment by bobbo** [comment]
There's a related parsing issue, where `i++` is parsed as `IncrementPost(IncrementPre(i))`

`    def: Block(
        [
            Expr {
                def: LetDecl(
                    [
                        (
                            "i",
                            Some(
                                Expr {
                                    def: Const(
                                        Num(
                                            0.0,
                                        ),
                                    ),
                                },
                            ),
                        ),
                    ],
                ),
            },
            Expr {
                def: UnaryOp(
                    IncrementPost,
                    Expr {
                        def: UnaryOp(
                            IncrementPre,
                            Expr {
                                def: Local(
                                    "i",
                                ),
                            },
                        ),
                    },
                ),
            },
        ],
    ),
}`

**Comment by jasonwilliams** [comment]
That’s odd, would need to see the tokens

**Comment by bobbo** [comment]
**JS**:
```
let i = 0;
i++
i
```

**Tokens**:
```
[src/lib/lib.rs:52] lexer.tokens = [
    Token {
        data: Keyword(
            Let,
        ),
        pos: Position {
            column_number: 1,
            line_number: 1,
        },
    },
    Token {
        data: Identifier(
            "i",
        ),
        pos: Position {
            column_number: 5,
            line_number: 1,
        },
    },
    Token {
        data: Punctuator(
            Assign,
        ),
        pos: Position {
            column_number: 7,
            line_number: 1,
        },
    },
    Token {
        data: NumericLiteral(
            0.0,
        ),
        pos: Position {
            column_number: 9,
            line_number: 1,
        },
    },
    Token {
        data: Punctuator(
            Semicolon,
        ),
        pos: Position {
            column_number: 10,
            line_number: 1,
        },
    },
    Token {
        data: Identifier(
            "i",
        ),
        pos: Position {
            column_number: 1,
            line_number: 2,
        },
    },
    Token {
        data: Punctuator(
            Inc,
        ),
        pos: Position {
            column_number: 2,
            line_number: 2,
        },
    },
    Token {
        data: Identifier(
            "i",
        ),
        pos: Position {
            column_number: 1,
            line_number: 3,
        },
    },
]
```

The tokens look reasonable from a quick glance. I've not had a proper dive into the parser but `parse` looks to emit the `IncrementPre` and `parse_next` the `IncrementPost`.

**Comment by jasonwilliams** [comment]
There should be a second semicolon after the Inc

**Comment by jasonwilliams** [comment]
Looks like it hits https://github.com/jasonwilliams/boa/blob/master/src/lib/syntax/parser.rs#L765-L770 first, which then calls parse again, that goes into https://github.com/jasonwilliams/boa/blob/master/src/lib/syntax/parser.rs#L565-L568

parse_next doesn't advance and so the next iteration it parses Inc again.
It might need some refactoring here, im not sure why it falls into parse_next

**Comment by jasonwilliams** [comment]
Taking a closer look, it looks like postIncrement was copied from preIncrement.

PreIncrement tries to parse the next token which is correct, but postIncrement shouldn’t do that, it already knows what it’s incrementing.
It should be taking the previous token (the identifier) and passing that as the argument (as a localExpr).
Let me know if none of this makes sense

**Comment by bobbo** [comment]
@jasonwilliams, thanks for the tips, will take a proper look at this as soon as possible.

**Comment by jasonwilliams** [comment]
@bobbo how was this going? need help?

**Comment by jasonwilliams** [comment]
Closing as the parsing side is fixed the rest will be implemented in https://github.com/jasonwilliams/boa/issues/321
