### ISSUE TITLE
[Feature] - BigInt

### ISSUE THREAD

**Issue by jasonwilliams** [jasonwilliams/boa#121]
https://tc39.es/ecma262/#sec-bigint-objects

**Comment by tiagolisalves** [comment]
I would like to implement this feature. I'm looking for resources to get some inspiration on how I could do efficient operations on big numbers.

**Comment by jasonwilliams** [comment]
Sure, go for it!

**Comment by jasonwilliams** [comment]
@tiagolisalves while you're in there, you mind looking at this too?
https://github.com/jasonwilliams/boa/blob/master/src/lib/syntax/lexer.rs#L395

**Comment by tiagolisalves** [comment]
@jasonwilliams Sure! I will give a look!

**Comment by HalidOdat** [comment]
If nobody is working on this I would like to implement it. :)

**Comment by Razican** [comment]
Should this still go in 0.8?

**Comment by HalidOdat** [comment]
> Should this still go in 0.8?

I should be done with `BigInt` #358 by today or tomorrow, I've been really busy this week so progress has been slow.

If there is a deadline for version 0.8 we can move this to 0.9.

**Comment by jasonwilliams** [comment]
> Should this still go in 0.8?

I don’t have strong opinions either way

**Comment by Razican** [comment]
> I should be done with `BigInt` #358 by today or tomorrow, I've been really busy this week so progress has been slow.

Ok, so I would say to add it, as it was initially planned for this version :)
