### ISSUE TITLE
[Easy] - rename js folder to builtins

### ISSUE THREAD

**Issue by jasonwilliams** [jasonwilliams/boa#123]
It would make sense to call `js` `builtins` instead, as that's mainly what it holds.
This would involve renaming the folder and updating the references.

Folder location:
https://github.com/jasonwilliams/boa/tree/master/src/lib/js

Debugging:
https://github.com/jasonwilliams/boa/blob/master/docs/debugging.md

**Comment by rajkharvar** [comment]
I will work on it. But I want to know which references are to be changed.

**Comment by jasonwilliams** [comment]
@rajkharvar You can do a find and replace for this https://github.com/jasonwilliams/boa/blob/master/src/lib/exec.rs#L3 `js::`

Also, the tests will most likely fail if you've missed a reference

**Comment by rajkharvar** [comment]
Okay, so I need to change all the `js::` to `builtins::`. Right??

**Comment by jasonwilliams** [comment]
@rajkharvar thats correct

**Comment by iRuler1337** [comment]
adad
