### ISSUE TITLE
[Easy] - consistency with how objects are added to Global

### ISSUE THREAD

**Issue by jasonwilliams** [jasonwilliams/boa#128]
object, console, math, function, json should follow the same pattern as String, Regex below
https://github.com/jasonwilliams/boa/blob/master/src/lib/realm.rs#L55-L59

## Example to follow:
Here is an example of Boolean being changed to `create_constructor` 
https://github.com/jasonwilliams/boa/commit/e35b66b41213cf519e85353b83b0952a95c4eda0#diff-9c85558881ecea17184e97fb52b0882b

**Comment by DomParfitt** [comment]
I'd be interested in having a go at this.
