### ISSUE TITLE
suggestion(demo): use Monaco Editor

### ISSUE THREAD

**Issue by WofWca** [jasonwilliams/boa#137]
https://microsoft.github.io/monaco-editor/index.html

I think this would make the project look more "professional". And convenient.

**Comment by StackDoubleFlow** [comment]
I would like to work on this one

**Comment by jasonwilliams** [comment]
@StackDoubleFlow  Sure

**Comment by StackDoubleFlow** [comment]
@jasonwilliams Oh I've already finished (#145)
