### ISSUE TITLE
Implement block scopes for let and const

### ISSUE THREAD

**Issue by jasonwilliams** [jasonwilliams/boa#14]
`let` has already been added to the [Keywords](https://github.com/jasonwilliams/boa/blob/master/src/lib/syntax/ast/keyword.rs#L119) enum which means if the lexer comes across it, it knows to create a new [Token](https://github.com/jasonwilliams/boa/blob/master/src/lib/syntax/ast/token.rs#L9-L14) for let.

The problem comes with the parser, as right now the parser doens't looks for let, so it fails at this point. 
The easy option to make things work would be to just add a `| Keyword::let` [here](https://github.com/jasonwilliams/boa/blob/master/src/lib/syntax/parser.rs#L78) but this means `let `would have the same semantics as `var`.

**What is different about let?**

Let is block scope, so it exist and then be popped off at the end of the closing scope. Right now we have scopes but they're only used when functions are created. Examples here:
https://github.com/jasonwilliams/boa/blob/master/src/lib/exec.rs#L168
https://github.com/jasonwilliams/boa/blob/master/src/lib/exec.rs#L352

So the fix is.. 
* Have a separate branch for let, which  creates a `LetDeclExpr` in  the parser.
* ~change scopes to function_scope so and have a new scopes for block scope, once we can differentiate between these we should be able to put `let`  declerations in the right place. This may be easier said than done, as block scopes will need to  inherit from function scopes and vice versa~
Actually we could just bump the scope for every block we come across instead, things should still work as normal. Start off by seeing how `var` works

Extra Info:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let
https://tc39.github.io/ecma262/#sec-let-and-const-declarations

*Research*
https://searchfox.org/mozilla-central/source/js/src/vm/EnvironmentObject.h#43

**Comment by jasonwilliams** [comment]
If a bar is created in a block scope we can’t add it to that scope as it will be removed when the block ends, so we will need to keep track of block and function scopes separately

**Comment by sisshiki1969** [comment]
In ECMA spec, the running execution context has references to two scopes (_LexicalEnvironmant_ and _VariableEnvironment_), which holds bindings in the block scope (let and const) and the function scope (var or functions declared by _FunctionDeclaration_) respectively.
https://tc39.github.io/ecma262/#table-23

**Comment by jasonwilliams** [comment]
So the general consensus is that i'm going to implement what's being laid out here:
https://tc39.github.io/ecma262/#sec-environment-records

This will replace the basic scope we have right now which is inside Interpreter

**Comment by jasonwilliams** [comment]
fixed by https://github.com/jasonwilliams/boa/pull/18
