### ISSUE TITLE
Create Print() function

### ISSUE THREAD

**Issue by jasonwilliams** [jasonwilliams/boa#142]
Arises from:
https://github.com/jasonwilliams/boa/issues/74

```
1. `print()` function in the global scope (or similar). SpiderMonkey's JavaScript shell defines this as: 
    > Evaluates the expression(s) and displays the result(s) on `stdout`, separated by spaces (" ") and terminated by a newline ("\n").
```

For Boa Shell we need a print function, the implementation is virtually the same as https://github.com/jasonwilliams/boa/blob/master/src/lib/js/console.rs#L11-L98

It might be worth abstracting the above logic into its own function, and have console.log() and print() use it.

print() should only be available in [shell](https://github.com/jasonwilliams/boa/blob/master/src/bin/shell.rs) 

So you will need to add it to the realm there.
You may need to create a helper function in realm which lets you add Objects to the global scope.

#### Spidermonkey equivalent
https://github.com/mozilla/gecko-dev/blob/master/js/src/shell/js.cpp#L2687-L2724

**Comment by Emanon42** [comment]
Interest in this. Can I take a try?

**Comment by jasonwilliams** [comment]
Sure!

**Comment by jasonwilliams** [comment]
In terms of the helper, there exists one in the spec:
https://tc39.es/ecma262/#sec-getglobalobject

The [Execution context](https://github.com/jasonwilliams/boa/blob/master/src/lib/exec.rs#L21-L27) should have a [getRealmObject](https://tc39.es/ecma262/#sec-getglobalobject) method. 
It might be worth returning a reference to the realm object for now. 

You will need this to add Print to the global object before running

**Comment by louisgjohnson** [comment]
if you call `print()` in the browser(chrome) it opens the printer prompt

**Comment by jasonwilliams** [comment]
@louisgjphnson this method won’t be in the final binary, only in the shell

**Comment by IovoslavIovchev** [comment]
@Emanon42 note that what we need is close to some of the work done in #171, so you can take a look (specifically having `Display`, `console.log` and `print` share some logic).

**Comment by Emanon42** [comment]
@IovoslavIovchev @jasonwilliams thanks! I have to delay my contribution on this issue because of my uni coursework :p 
I will finish this before December!

**Comment by IovoslavIovchev** [comment]
@Emanon42 no worries, take your time
