### ISSUE TITLE
Rest / Spread operator

### ISSUE THREAD

**Issue by jasonwilliams** [jasonwilliams/boa#151]
This is needed

**Comment by robertmaloney** [comment]
Can I pick this up?

**Comment by jasonwilliams** [comment]
Sure

**Comment by jasonwilliams** [comment]
@robertmaloney everything ok on this?

**Comment by robertmaloney** [comment]
Apologies for being slow with this. I already have function spread and working on wrapping arrow functions, and I think that'd be a good point to get a PR in.

**Comment by jasonwilliams** [comment]
This is now working for arrays and function arguments, objects are still not supported but i will open a new ticket for that
