### ISSUE TITLE
[Lexer] Unicode Escape Sequence

### ISSUE THREAD

**Issue by LuoZijun** [jasonwilliams/boa#16]
Lines: https://github.com/jasonwilliams/boa/blob/master/src/lib/syntax/lexer.rs#L237-L240

It seems that support for Unicode escape sequences is not perfect. Is there a plan to create a complete Lexer and Parser ?

**Comment by jasonwilliams** [comment]
@LuoZijun thanks for raising this.
Hopefully if i can, but if it proves too difficult we can switch to using a complete lever and parser already available.
It’s not a decision I’ve made yet, was this something you wanted to work on?

**Comment by LuoZijun** [comment]
I'm trying to write a complete Lexer and Parser, But not not finished yet :(

https://github.com/LuoZijun/es

**Comment by jasonwilliams** [comment]
@LuoZijun that’s awesome!
Maybe room for collaboration or to share some tips? What’s the best way to contact you?

**Comment by LuoZijun** [comment]
Yeah, I think we can share the same parser in the future ( Maybe ).

Email: luozijun.assistant@gmail.com
