### ISSUE TITLE
Implement Array.prototype.every()

### ISSUE THREAD

**Issue by jasonwilliams** [jasonwilliams/boa#163]
Array methods are implemented here, for e.g here's concat:
https://github.com/jasonwilliams/boa/blob/master/src/lib/js/array.rs#L78-L109

**Specification:**
https://tc39.es/ecma262/#sec-array.prototype.every

**Contributing & Debugging**
https://github.com/jasonwilliams/boa#contributing
https://github.com/jasonwilliams/boa/blob/master/docs/debugging.md

**Comment by Korpen** [comment]
I'd like to tackle this
