### ISSUE TITLE
Implement Array.prototype.fill()

### ISSUE THREAD

**Issue by jasonwilliams** [jasonwilliams/boa#164]
Array methods are implemented here, for e.g here's concat:
https://github.com/jasonwilliams/boa/blob/master/src/lib/js/array.rs#L78-L109

**Specification:**
https://tc39.es/ecma262/#sec-array.prototype.fill

**Contributing & Debugging**
https://github.com/jasonwilliams/boa#contributing
https://github.com/jasonwilliams/boa/blob/master/docs/debugging.md

**Comment by bojan88** [comment]
Can I take this one?
