### ISSUE TITLE
Implement Array.prototype.find()

### ISSUE THREAD

**Issue by jasonwilliams** [jasonwilliams/boa#165]
Array methods are implemented here, for e.g here's concat:
https://github.com/jasonwilliams/boa/blob/master/src/lib/js/array.rs#L78-L109

**Specification:**
https://tc39.es/ecma262/#sec-array.prototype.find

**Contributing & Debugging**
https://github.com/jasonwilliams/boa#contributing
https://github.com/jasonwilliams/boa/blob/master/docs/debugging.md

**Comment by rodrigocam** [comment]
I will work on this!
