### ISSUE TITLE
Implement Array.prototype.findIndex()

### ISSUE THREAD

**Issue by jasonwilliams** [jasonwilliams/boa#166]
Array methods are implemented here, for e.g here's concat:
https://github.com/jasonwilliams/boa/blob/master/src/lib/js/array.rs#L78-L109

**Specification:**
https://tc39.es/ecma262/#sec-array.prototype.findIndex

**Contributing & Debugging**
https://github.com/jasonwilliams/boa#contributing
https://github.com/jasonwilliams/boa/blob/master/docs/debugging.md

**Comment by felipe-fg** [comment]
Hey, @jasonwilliams.

I'm interested in this one. Can I give it a try?

**Comment by jasonwilliams** [comment]
@felipe-fg sure
