### ISSUE TITLE
Implement Array.prototype.slice()

### ISSUE THREAD

**Issue by jasonwilliams** [jasonwilliams/boa#177]
Array methods are implemented here, for e.g here's concat:
https://github.com/jasonwilliams/boa/blob/master/src/lib/js/array.rs#L78-L109

**Specification:**
https://tc39.es/ecma262/#sec-array.prototype.slice

**Contributing & Debugging**
https://github.com/jasonwilliams/boa#contributing
https://github.com/jasonwilliams/boa/blob/master/docs/debugging.md

**Comment by muskuloes** [comment]
I'll like to be assigned to this.

**Comment by IovoslavIovchev** [comment]
Done in #180
