### ISSUE TITLE
Implement the Tilde operator

### ISSUE THREAD

**Issue by IovoslavIovchev** [jasonwilliams/boa#179]
Currently the `~` operator causes a `parsing failed` exception.

_Tilde_ performs a bitwise [NOT](https://en.wikipedia.org/wiki/Bitwise_operation#NOT).

---

**Example:**
```javascript
let x = 0x01;
x = ~x;

console.log(x); // -2
```

**Comment by letmutx** [comment]
I'd like to work on this.
