### ISSUE TITLE
Should check for existence of binding before creating a new one

### ISSUE THREAD

**Issue by jasonwilliams** [jasonwilliams/boa#19]
Take this javascript..
```js
let a = "foo";
a = "bar";
```

The error message we get is 
```
thread 'main' panicked at 'Binding already exists!', src/lib/environment/global_environment_record.rs:108:13
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

This is because rather than re-using `a` the interpreter is attempting to create a new binding called `a` which already exists so causes an error.

https://github.com/jasonwilliams/boa/blob/master/src/lib/exec.rs#L333-L337 needs to be more clever. there needs to be a check here to see if the binding already exists, if it does use that binding and set it to a new value.

### What does the spec say?
https://tc39.github.io/ecma262/#sec-assignment-operators-runtime-semantics-evaluation
https://tc39.github.io/ecma262/#sec-putvalue

**Comment by perfectmak** [comment]
@jasonwilliams is this still available, I would like to work on it to better understand how boa works

**Comment by jasonwilliams** [comment]
Sure go for it @perfectmak
