### ISSUE TITLE
Create a macro for properly setting builtin member functions

### ISSUE THREAD

**Issue by IovoslavIovchev** [jasonwilliams/boa#193]
When creating a new member function for some `builtin`, you need to make sure the `create_constructor()` function contains this:
```rust
let some_func = to_value(func as NativeFunctionData);
some_func.set_field_slice("length", to_value(1_i32));

// .. and then
some_prototype.set_field_slice("someFunc", some_func); 
``` 

Writing these two lines for each new function can prove tedious _and_ error prone, as the second line can be missed when needed ([functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/length) have their `length` property reflect the number of arguments they accept).

What I propose is the following macro:
```rust
make_fn!(some_func, named "someFunc", with length 1, of some_prototype);
```
which will essentially contain the 3 aforementioned boilerplate lines.

What I am saying should definitely not be set in stone. It is only supposed to start a discussion on the topic.

**Comment by jasonwilliams** [comment]
This is a good idea, although i wonder if it will overlap [Function Objects ](https://tc39.es/ecma262/#sec-createbuiltinfunction)

**Comment by IovoslavIovchev** [comment]
Depends on what you mean by "functions we come across in code".
My intention is for it to only be used for reducing boilerplate in _buil-tins_.

It is a more humble version of `CreateBuiltinFunction` (of which I found no implementation, apologies if I am missed anything). Of course, we could expand the scope a bit here and fully implement `CreateBuiltinFunction`.

**Comment by IovoslavIovchev** [comment]
Great. I believe it will be a good first issue.

Will mark it as such, if anyone is interested.

**Comment by Stupremee** [comment]
I can take care of this

**Comment by Stupremee** [comment]
This issue can be closed I guess

**Comment by IovoslavIovchev** [comment]
Done as part of #206

**Comment by thiagoarrais** [comment]
I'm getting `undefined` when I do `'abc'.matchAll.length` in `tests.js`. Even after upgrading to 7698873. Am I doing something wrong?

**Comment by Stupremee** [comment]
I think a new issue for your issue would be better @thiagoarrais

**Comment by thiagoarrais** [comment]
Sure!
