### ISSUE TITLE
[Question] What is mk macro used for?

### ISSUE THREAD

**Issue by flopacero** [jasonwilliams/boa#207]
I was looking around codebase trying to work with one of a bug issue. I stumbled upon several nonobvious moments in codebase. 

One of them is `mk` macro. Confusing moments:
  * There are two cases in macro but it ignores all its arguments but one. What are other arguments for?
  * As far as I can see what it does it just creates `Entity` with `Entity::new` which can be done without macro at all. Why is macro then?

Thanks

**Comment by IovoslavIovchev** [comment]
It used to have a different definition, but at one point they were removed (see #2) because they were deemed unnecessary.
