### ISSUE TITLE
[Question] Why semicolon doesn't stop expression parsing?

### ISSUE THREAD

**Issue by flopacero** [jasonwilliams/boa#208]
This is a question about codebase. As far as I get there is `parse` function to parse a single expression which uses `parse_next` to look ahead along with several others. Currently if `parse_next` sees semicolon it advances position but does not stop expression parsing. Why is so? I thought thaat it should denote the end of expression.

It causes at least one of the reported problem with pre-increment/pre-decrement operator.

Thanks

**Comment by jasonwilliams** [comment]
Hi @flopacero 

You're right, i don't think that's correct and has probably never been changed.
Do you have a test cases which breaks this?

**Comment by adumbidiot** [comment]
This:
```
var a = 1;
+ 1;
a
```
returns 2.

**Comment by jasonwilliams** [comment]
Thanks @adumbidiot will try that test case and see if there’s any fixes that can be made

**Comment by Razican** [comment]
Is this still happening with the new parser?

**Comment by HalidOdat** [comment]
> Is this still happening with the new parser?

After some testing this does not seem to happen.
The code:
```
var a = 1;
+ 1;
a
```
Ater running running: `cargo run -- test.js --dump-ast`:
```text
StatementList(
    [
        VarDecl(
            [
                (
                    "a",
                    Some(
                        Const(
                            Num(
                                1.0,
                            ),
                        ),
                    ),
                ),
            ],
        ),
        UnaryOp(
            Plus,
            Const(
                Num(
                    1.0,
                ),
            ),
        ),
        Local(
            "a",
        ),
    ],
)
```
It's parsing correctly and returns as expected `1` not `2`. :+1:

**Comment by Razican** [comment]
Nice, I added a test for this in #303.
