### ISSUE TITLE
Use as a rust crate

### ISSUE THREAD

**Issue by shekohex** [jasonwilliams/boa#21]
Hi 😃, great work and great crate, i would like to use this crate in my projects to provide some sort of dynamic logic for my application, currently checking out this crate in crates.io i found it uses other dependencies that could be optional for example the `wasm-bindgen`.

I mean it would be great to split it up into two crates for example `boa-core` and `boa-wasm` or maybe just make the `wasm-bindgen` for example an optional dependency behind a feature flag, also to avoid break the world it could be enabled by default, that also would be great.

Thank you 😊

**Comment by jasonwilliams** [comment]
Thanks @shekohex i will look into this, i think for now i will make `wasm-bindgen` an optional dep

**Comment by shekohex** [comment]
Thank you very much, By the way if you wish to close this issue for now, i have no problem at all, also if you want to keep it open and you are planning to split the entire engine up to small crates that also would be awesome :+1:

**Comment by jasonwilliams** [comment]
Sounds good, I will close this and we can re-open another issue for splitting
