### ISSUE TITLE
Make "structopt" dependency optional

### ISSUE THREAD

**Issue by adumbidiot** [jasonwilliams/boa#239]
The `structopt` dependency seems to be only used for the binaries. It would be nice if it could be disabled if this engine was used as a library. Maybe it could be put behind a `cli` feature flag or similar and enabled for the binaries only?

**Comment by jasonwilliams** [comment]
@adumbidiot that sounds fine to me, is this something you wanted to look at?

**Comment by adumbidiot** [comment]
Yeah sure

**Comment by Razican** [comment]
Another option would be to separate the crate into two: `boa` and `boa-cli`, in the same workspace. This would allow for differentiating the CLI from the library itself, and not require features: each crate would have its own dependencies, and share them if compiled together.

**Comment by jasonwilliams** [comment]
@Razican sounds interesting, would it still be easy to develop against the CLI when working against the lib? Ive not split 2 crates in the same project before

**Comment by Razican** [comment]
@jasonwilliams it should be easy, yes. Both crates would be in the same repo, with a `Cargo.toml` especifying the workspace. The `Cargo.lock` file would be at a workspace level. A huge example with multiple crates can be seen with [`diesel`][diesel].

I can do a PR this week to see how it would look like, but I think it should be fairly easy.

[diesel]: https://github.com/diesel-rs/diesel
