### ISSUE TITLE
Make `bin` binary nicer

### ISSUE THREAD

**Issue by adumbidiot** [jasonwilliams/boa#246]
It would be nice if `bin` properly printed the result to stdout and not debug the result of the execution. It would also be great if it could have some flags to dump tokens or the ast when trying to debug.

**Comment by HalidOdat** [comment]
I'm on it. :+1:

**Comment by HalidOdat** [comment]
I added this functionality in a branch. 
The dump functionality works both for files and REPL.

With --dump-tokens and --dump-ast to dump to stdout.

The dumping of tokens and ast is mutually exclusive and when dumping it wont run the code.

Here is the pull request https://github.com/jasonwilliams/boa/pull/278

**Comment by HalidOdat** [comment]
This issue should be closed the branch that implements this feature #278 has already been merged. :+1:
