### ISSUE TITLE
Implement the "this" keyword

### ISSUE THREAD

**Issue by Razican** [jasonwilliams/boa#264]
The `this` [keyword][this_keyword] returns an expression dependent on the context where it's being used. This context is resolved by the [`ResolveThisBinding()`][resolve_this] abstract operation. This abstract operation will get the current environment record, and return the `this` binding, if any.

The MDN [documentation][mdn_docs] also explains how this keyword will resolve to a different expression depending on how it's called.

To implement this, we require changes to the parser, where keywords are parsed ([parser.rs#L112][struct_parsing]), which will probably require a new `ExprDef`. Executing that expression in the executor, it should return the object representing the `this` binding.

[this_keyword]: https://tc39.es/ecma262/#sec-this-keyword
[resolve_this]: https://tc39.es/ecma262/#sec-resolvethisbinding
[mdn_docs]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this
[struct_parsing]: https://github.com/jasonwilliams/boa/blob/master/boa/src/syntax/parser.rs#L112

**Comment by jasonwilliams** [comment]
Thanks for making this

**Comment by Razican** [comment]
I just noticed that #185 exists.

**Comment by jasonwilliams** [comment]
it does but its quite an old pr now
