### ISSUE TITLE
Weird behavior with JSON builtin

### ISSUE THREAD

**Issue by vlakreeh** [jasonwilliams/boa#269]
The JSON built in currently has a few issues that are thankfully easy to fix.Currently the `JSON.stringify` and `JSON.parse` are undefined and expect you to specify the `JSON` builtin's prototype.

The second issue is that the function `JSON.stringify` *(accessed through `JSON.prototype.stringify`)* returns unexpected output.

Example:

```javascript
JSON.prototype.stringify({ number: 1 }) // Currently evaluates to "{ "extensible": true }"
```

This issue seems to be caused by [this line](https://github.com/jasonwilliams/boa/blob/master/boa/src/builtins/value/mod.rs#L594) using the `internal_slots` instead of the object's properties.

If you want I could submit a PR to fix these issues.

**Comment by jasonwilliams** [comment]
Yes please @vlakreeh i don't know why its iterating through internal slots there instead of properties, seems odd. Looks like a change i made but not sure why i did that.

**Comment by Razican** [comment]
I think that #325 solved the first issue described here, and the other issue seems to be solved. If I run:
```javascript
JSON.stringify({ number: 1 })
```
I get:
```json
{"number":1}
```

And, in a more complex scenario:
```javascript
let a = JSON.stringify({ number: 1 });
let b = JSON.parse(a);
b.number;
```
I get `1`.

So I'm closing this issue.
