### ISSUE TITLE
Do we get rid of expect_no_lineterminator?

### ISSUE THREAD

**Issue by jasonwilliams** [jasonwilliams/boa#299]
It’s causing warnings and It seems we don’t use it.

@Razican @HalidOdat

**Comment by HalidOdat** [comment]
I think we should remove it, there is no use for it. I would like to know what @Razican thinks of it.

**Comment by Razican** [comment]
I think I removed it in #295, that is ready to be merged, so sure, it doesn't make much sense to have something that we don't use.
