### ISSUE TITLE
Migrate from time to Chrono

### ISSUE THREAD

**Issue by jasonwilliams** [jasonwilliams/boa#3]
the time crate is deprecated and Chrono seems to be the replacement. We should move to this

**Time**
https://crates.io/crates/time
https://docs.rs/time/0.1.40/time/

**Chrono**
https://crates.io/crates/chrono
https://docs.rs/chrono/0.4.6/chrono/

**More Info**
https://github.com/rust-lang-deprecated/time/issues/136

**Comment by JasonShin** [comment]
I don't know Rust but I'm keen on helping it out

**Comment by jasonwilliams** [comment]
this has now been fixed thanks @AFRUITPIE !
