### ISSUE TITLE
Adding more labels for issues

### ISSUE THREAD

**Issue by HalidOdat** [jasonwilliams/boa#319]
I think we should add more labels, so we can keep track of what is what and be more organized.
Currently I added `Documentation` and `Lexer` but i think we should add more as described in [**Labels used for issues**](https://github.com/dotnet/roslyn/wiki/Labels-used-for-issues)

what do you think? @Razican @jasonwilliams

**Comment by jasonwilliams** [comment]
Sure, i really like the Easy, Medium, Hard labels also (I think Servo used these) makes it easy for new contributors to know what to pick up

**Comment by Razican** [comment]
I think we have enough labels now, right?

**Comment by HalidOdat** [comment]
> I think we have enough labels now, right?

I guess we have enough labels now. If there is a need we will add more. :)
