### ISSUE TITLE
Any tasks for a rust/programming beginner? 

### ISSUE THREAD

**Issue by logotie** [jasonwilliams/boa#32]
Would there be any tasks for a Rust beginner to do? Would definitely like to contribute some code :)

**Comment by jasonwilliams** [comment]
Sure! Give me a couple of days to create some issues

**Comment by logotie** [comment]
Thank you so much!  :)

**Comment by jasonwilliams** [comment]
https://github.com/jasonwilliams/boa/issues/35 would be a useful one

**Comment by jasonwilliams** [comment]
@logotie there are quite a few "good first issue"s now i can also answer any Qs

**Comment by logotie** [comment]
Thanks for taking the time out to add some issues @jasonwilliams !  I am browsing through them now :)

**Comment by jasonwilliams** [comment]
@logotie np https://github.com/jasonwilliams/boa/issues/47 is a nice small one

**Comment by jasonwilliams** [comment]
https://github.com/jasonwilliams/boa/issues/72 is also very small
