### ISSUE TITLE
After #326, we cannot generate documentation for the boa library

### ISSUE THREAD

**Issue by Razican** [jasonwilliams/boa#329]
So, it seems that now that the CLI binary is called `boa`, the documentation is being output in `target/doc/boa` for both the binary and the library, and rustdoc just ignores the library.

So we need to either revert that PR, change the name of the library crate (to `boa_core` or something similar), or find a way to avoid this through configuration options.

**Comment by HalidOdat** [comment]
Hmmm. I will look into it to find a better solution. :)

**Comment by HalidOdat** [comment]
We could: 
 - disable documentation on the binary with `doc = false`
 - revert the changes.

What do you think? @Razican

**Comment by Razican** [comment]
Hmmm maybe not generating documentation for the binary makes sense. There is basically no documentation anyway, and the code is simple enough (at least for now).

Let's see what @jasonwilliams thinks.

**Comment by jasonwilliams** [comment]
I agree with @Razican I’m ok with not generating documentation for the binary, that would be my choice right now.
