### ISSUE TITLE
Change all r#try! to ? 

### ISSUE THREAD

**Issue by jasonwilliams** [jasonwilliams/boa#33]
Rust 2018 edition removed the need for the `try` macro, functions which return an Option/Result can be used with the `?` operator.

**More info here:**
https://doc.rust-lang.org/stable/edition-guide/rust-2018/error-handling-and-panics/the-question-mark-operator-for-easier-error-handling.html

Book:
https://doc.rust-lang.org/beta/book/ch09-02-recoverable-errors-with-result.html#a-shortcut-for-propagating-errors-the--operator

Boa still has `try!` all over the place for e.g https://github.com/jasonwilliams/boa/blob/master/src/lib/js/value.rs#L507

These could be converted to use the ? operator instead. e.g https://github.com/jasonwilliams/boa/blob/master/src/lib/syntax/lexer.rs#L219

**Comment by Atul9** [comment]
Hi @jasonwilliams I would like to take this up.
