### ISSUE TITLE
We only get `Const::Num`, never `Const::Int`

### ISSUE THREAD

**Issue by HalidOdat** [jasonwilliams/boa#331]
This is a bug in the lexer.

Currently we only have one numerical token type `NumericalLiteral` which is of type `f64`, hence all numerical values are converted to `f64` and we only get `Cont::Num`.

This bug blocks #328

**Comment by jasonwilliams** [comment]
What scenarios do we get int?
On phone at the moment so cant load up the spec

**Comment by Razican** [comment]
> What scenarios do we get int?

As per the spec, a [`NumericLiteral`](https://tc39.es/ecma262/#prod-NumericLiteral) is one of
 - `DecimalLiteral`
 - `DecimalBigIntegerLiteral`
 - `NonDecimalIntegerLiteral`
 - `NonDecimalIntegerLiteral` `BigIntLiteralSuffix`

So it seems we need to take into accounts integers as a separate type. This seems to be used for octal, hexadecimal and binary representations too.
