### ISSUE TITLE
Make WASM an opt-in feature

### ISSUE THREAD

**Issue by Razican** [jasonwilliams/boa#333]
Currently, webassembly is an opt-out feature. While we use it for the web example, I think in the future it will be more common for Boa to be used as a library than as webassembly.

In this scenario, I think it's best to make the feature opt-in, so that we don't need to use `default-features = false` when loading the crate as a library.

This would mean that we need somehow to be able to select a feature in wasm-pack, or that we need a different crate only exporting boa as wasm, in the workspace, something like `boa-wasm`.

I would go for this second option, as it also allows us to add `#![forbid(unsafe_code)]` at the crate level in `boa`.

What do you think?

**Comment by HalidOdat** [comment]
> This would mean that we need somehow to be able to select a feature in wasm-pack, or that we need a different crate only exporting boa as wasm, in the workspace, something like `boa-wasm`.

I also think this is a good idea as it would allow us to move the most of the webassembly stuff in that directory, making think more organized.

And not having to specify that the `default-features = false` is awesome as the default features should be features that every one needs by default.

**Comment by jasonwilliams** [comment]
Yep agree with the above it should be opt in rather than opt out.

**Comment by muskuloes** [comment]
I would like to take this one. But will only be able to work on it from next week, if that's ok.

**Comment by Razican** [comment]
> I would like to take this one. But will only be able to work on it from next week, if that's ok.

Sure, go ahead, let us know when you start! :)

**Comment by muskuloes** [comment]
I can start now.
