### ISSUE TITLE
Read from input instead of hardcoded to file

### ISSUE THREAD

**Issue by jasonwilliams** [jasonwilliams/boa#35]
Running boa will always read from the same file, at some point we will need to read from any file that is pased through.

Parsing arguments example:
https://doc.rust-lang.org/beta/rust-by-example/std_misc/arg/matching.html

https://github.com/jasonwilliams/boa/blob/master/src/bin/bin.rs#L6 can be changed to read from the command line argument (similar to NodeJS)

Maybe `tests/js/test.js` can be read as a fallback?

**Comment by jasonwilliams** [comment]
This would really help with https://github.com/jasonwilliams/boa/issues/12

**Comment by callumquick** [comment]
Gonna take this one since I think it will also help with testing or setting up better automated tests for the "methods of objects" we've been implementing (check behaviour is as expected with Javascript directly). Also, any closer we get to Test 262 the better.
