### ISSUE TITLE
`Abstract Equality Comparison impl` implementation

### ISSUE THREAD

**Issue by hello2dj** [jasonwilliams/boa#351]
- [x] https://github.com/jasonwilliams/boa/pull/383

`[] == ![]` should equal `true` not `false`.

more info:
[ECMAScript specification](https://www.ecma-international.org/ecma-262/10.0/index.html#sec-abstract-equality-comparison)

**Comment by Razican** [comment]
Good catch thanks! I'll try to check how to fix it and propose it as a good first issue :)

**Comment by Razican** [comment]
This is implemented in https://github.com/jasonwilliams/boa/blob/master/boa/src/builtins/value/mod.rs#L882-L903

It seems that this is not 100% spec compliant. So the idea is to change that code to be follow the algorithm in the spec.

**Comment by hello2dj** [comment]
i am newbee. But I want to try.

**Comment by HalidOdat** [comment]
> i am newbee. But I want to try

Sure, go for it.

**Comment by Razican** [comment]
> i am newbee. But I want to try.

Let us know if you need any help!

**Comment by hello2dj** [comment]
I'm working on it now, i have a quetion, this code https://github.com/jasonwilliams/boa/blob/master/boa/src/exec/mod.rs#L394-L406
why use `borrow_mut`.

`In particular Eq, Ord and Hash must be equivalent for borrowed and owned values: x.borrow() == y.borrow() should give the same result as x == y.` 
[moreinfo](https://doc.rust-lang.org/std/borrow/trait.Borrow.html)

**Comment by Razican** [comment]
> why use `borrow_mut`.

Actually, I have no clue. Maybe @jasonwilliams can give a hint here. In any case, if you can make it work without a `mut`, that would be great!

**Comment by hello2dj** [comment]
> This is implemented in https://github.com/jasonwilliams/boa/blob/master/boa/src/builtins/value/mod.rs#L882-L903
> 
> It seems that this is not 100% spec compliant. So the idea is to change that code to be follow the algorithm in the spec.

only changing this code is not enough. we need to implement `Abstract Equality Comparison`. And this need call `to_primitive` which implment on `Interpreter`. Personally, I think `Abstract Equality Comparison` is a recursive algorithm, but the current structure of `ValueData` is not friendly to implement that.

So,  In my opinion, we need to implement that on `Interpreter`, not ValueData

more info:
[ECMAScript specification](https://www.ecma-international.org/ecma-262/10.0/index.html#sec-abstract-equality-comparison)
[to_primitive](https://github.com/jasonwilliams/boa/blob/master/boa/src/exec/mod.rs#L683)

**Comment by Razican** [comment]
> > This is implemented in [/boa/src/builtins/value/mod.rs@`master`#L882-L903](https://github.com/jasonwilliams/boa/blob/master/boa/src/builtins/value/mod.rs#L882-L903) [](/jasonwilliams/boa/blob/HEAD@{2020-05-09T02:56:13Z}/boa/src/builtins/value/mod.rs#L882-L903)
> > It seems that this is not 100% spec compliant. So the idea is to change that code to be follow the algorithm in the spec.
> 
> only changing this code is not enough. we need to implement `Abstract Equality Comparison`. And this need call `to_primitive` which implment on `Interpreter`. Personally, I think `Abstract Equality Comparison` is a recursive algorithm, but the current structure of `ValueData` is not friendly to implement that.
> 
> So, In my opinion, we need to implement that on `Interpreter`, not ValueData
> 
> more info:
> [ECMAScript specification](https://www.ecma-international.org/ecma-262/10.0/index.html#sec-abstract-equality-comparison)
> [to_primitive](https://github.com/jasonwilliams/boa/blob/master/boa/src/exec/mod.rs#L683) [](/jasonwilliams/boa/blob/HEAD@{2020-05-09T02:56:13Z}/boa/src/exec/mod.rs#L683)

Good point, we don't have a spec-compliant equality comparison. We should properly implement the spec in this area, for both the strict equality and the abstract equality.

About where to implement it, maybe `toPrimitive` should be in the interpreter, but maybe the function should be passed as a parameter to the abstract equality function in the value. @HalidOdat what do you think?

Also, merging #383 will change this a bit too.

**Comment by hello2dj** [comment]
> > > This is implemented in [/boa/src/builtins/value/mod.rs@`master`#L882-L903](https://github.com/jasonwilliams/boa/blob/master/boa/src/builtins/value/mod.rs#L882-L903) 
> > > It seems that this is not 100% spec compliant. So the idea is to change that code to be follow the algorithm in the spec.
> > 
> > 
> > only changing this code is not enough. we need to implement `Abstract Equality Comparison`. And this need call `to_primitive` which implment on `Interpreter`. Personally, I think `Abstract Equality Comparison` is a recursive algorithm, but the current structure of `ValueData` is not friendly to implement that.
> > So, In my opinion, we need to implement that on `Interpreter`, not ValueData
> > more info:
> > [ECMAScript specification](https://www.ecma-international.org/ecma-262/10.0/index.html#sec-abstract-equality-comparison)
> > [to_primitive](https://github.com/jasonwilliams/boa/blob/master/boa/src/exec/mod.rs#L683)
> 
> Good point, we don't have a spec-compliant equality comparison. We should properly implement the spec in this area, for both the strict equality and the abstract equality.
> 
> About where to implement it, maybe `toPrimitive` should be in the interpreter, but maybe the function should be passed as a parameter to the abstract equality function in the value. @HalidOdat what do you think?
> 
> Also, merging #383 will change this a bit too.

Yes, that is what I need. I should wait for https://github.com/jasonwilliams/boa/pull/383.

**Comment by HalidOdat** [comment]
> About where to implement it, maybe `toPrimitive` should be in the interpreter, but maybe the function should be passed as a parameter to the abstract equality function in the value. @HalidOdat what do you think?

Alternatively we cold make the `toPrimitive` a free function that takes a `Value` and the context (interpreter), instead of it living in interpreter.

V8 implementation [here](https://github.com/v8/v8/blob/master/src/objects/objects.cc#L699-L798)

**Comment by Razican** [comment]
> > About where to implement it, maybe `toPrimitive` should be in the interpreter, but maybe the function should be passed as a parameter to the abstract equality function in the value. @HalidOdat what do you think?
> 
> Alternatively we cold make the `toPrimitive` a free function that takes a `Value` and the context (interpreter), instead of it living in interpreter.
> 
> V8 implementation [here](https://github.com/v8/v8/blob/master/src/objects/objects.cc#L699-L798) [](/v8/v8/blob/HEAD@{2020-05-09T12:30:08Z}/src/objects/objects.cc#L699-L798)

Hmmm I think that what we are trying to convert to a primitive is the value, right? I think it would have more semantic sense in `Value` than in the wild.

> I should wait for #383.

It has been merged! :tada: as soon as we decide on a design, I think it's safe to start implementing it :)

**Comment by HalidOdat** [comment]
> I think it would have more semantic sense in `Value` than in the wild.

Yes. This is probably the best choice.

**Comment by hello2dj** [comment]
> > I think it would have more semantic sense in `Value` than in the wild.
> 
> Yes. This is probably the best choice.

we also need a static method which is the same function as `Interpreter.call`. This may be a huge work. According to my current understanding of boa, I can't do it.

**Comment by Razican** [comment]
> we also need a static method which is the same function as `Interpreter.call`. This may be a huge work. According to my current understanding of boa, I can't do that.

What do you mean? Where do we need it?

**Comment by hello2dj** [comment]
sorry, My description is too vague. `Abstract Equality Comparison` -> `to_primitive` -> 'ordinary_to_primitive' -> 'Interpreter.call'

more info
[boa to_primitive](https://github.com/jasonwilliams/boa/blob/master/boa/src/exec/mod.rs#L692-L747)
[v8 Abstract Equality Comparison](https://github.com/v8/v8/blob/master/src/objects/objects.cc#L790)

**Comment by Razican** [comment]
> @Razican sorry, My description is too vague. `Abstract Equality Comparison` -> `to_primitive` -> 'ordinary_to_primitive' -> 'Interpreter.call'

Can't we pass a reference to the `Interpreter` around?

**Comment by hello2dj** [comment]
> > @Razican sorry, My description is too vague. `Abstract Equality Comparison` -> `to_primitive` -> 'ordinary_to_primitive' -> 'Interpreter.call'
> 
> Can't we pass a reference to the `Interpreter` around?

I will try it

**Comment by Razican** [comment]
> I will try it

Thanks! :D

**Comment by hello2dj** [comment]
I implement a recursive version expect BigInt & NaN which boa doesn't implement them(or I am wrong). I need to do some testing on it and optimize it.

**Comment by Razican** [comment]
> I implement a recursive version expect BigInt & NaN which boa doesn't implement them(or I am wrong). I need to do some testing on it and optimize it.

This sounds great! As you say BigInt is not yet supported by Boa, it's being implemented by @HalidOdat in #358.

About `NaN`, we do support it via a `f64::NAN`, so it's considered a normal numeric type.

**Comment by hello2dj** [comment]
> NAN

I mean parser doesn't receive `NaN`, you can try 
```js
console.log(typeof NaN);  // `number`  is right
```
boa executes this script will panic. I will open an issue.

**Comment by Razican** [comment]
> > NAN
> 
> I mean parser doesn't receive `NaN`, you can try 
> ```js
> console.log(typeof NaN);  // `number`  is right
> ```
> boa executes this script will panic. I will open an issue.

Good catch! I'll give it a look to see what's happening.
