### ISSUE TITLE
`"-0" == 0` and `"+0" == 0` returns `false`, it should return `true`

### ISSUE THREAD

**Issue by HalidOdat** [jasonwilliams/boa#357]
The expression `"0" == 0` returns `true` as expected, but `"-0" == 0` and `"+0" == 0` returns `false`, when it should return `true`.

More information: [ECMAScript specification](https://tc39.es/ecma262/#sec-abstract-equality-comparison)

**Comment by Razican** [comment]
I think this is also related to #351. We seem to have a bit of a mess with the equality of values.

**Comment by HalidOdat** [comment]
Yeah. When I was trying to implement the bigint feature i noticed that its not spec compliant.
