### ISSUE TITLE
TypeOf failing

### ISSUE THREAD

**Issue by jasonwilliams** [jasonwilliams/boa#359]
TypeOf is defined as both a Node:
https://github.com/jasonwilliams/boa/blob/master/boa/src/syntax/ast/node.rs#L421

And a UnaryOp Variant:
https://github.com/jasonwilliams/boa/blob/master/boa/src/syntax/parser/expression/unary.rs#L58-L60

looking at the spec it seems the former is what we should keep and we should remove it from being a unary variant. 

Right now the variant is being used but there's no implementation on the [exec side](https://github.com/jasonwilliams/boa/blob/master/boa/src/exec/mod.rs#L314)

Make some JS, like this to test.
```
const a = String();
typeof a;
```

I'm not sure we will need https://github.com/jasonwilliams/boa/blob/master/boa/src/builtins/value/mod.rs#L631-L651 once Node::TypeOf is being used.

**Spec:**
https://tc39.es/ecma262/#sec-typeof-operator

**Debugging**
https://github.com/jasonwilliams/boa/blob/master/docs/debugging.md

**Comment by RestitutorOrbis** [comment]
I'm willing to take this on if no one else is already.

**Comment by Razican** [comment]
> I'm willing to take this on.

Hoy ahead! Let us know if you need help!

**Comment by Razican** [comment]
> looking at the spec it seems the former is what we should keep and we should remove it from being a unary variant.

How do we decide this? Looking at the spec, it does seem indeed to be a unary operator, right?

**Comment by jasonwilliams** [comment]
> > looking at the spec it seems the former is what we should keep and we should remove it from being a unary variant.
> 
> How do we decide this? Looking at the spec, it does seem indeed to be a unary operator, right?

You’re right now I see it’s a unary expression

**Comment by Razican** [comment]
> You’re right now I see it’s a unary expression

In this case, I think it's best to implement it as a unary expression and remove the `Node`.
