### ISSUE TITLE
Symbol can be an Object type instead of a native type

### ISSUE THREAD

**Issue by jasonwilliams** [jasonwilliams/boa#364]
Symbol is currently a native type on [ValueData](https://github.com/jasonwilliams/boa/blob/master/boa/src/builtins/value/mod.rs#L40-L60).

It doesn't need to be, it can be an Object with it's kind set to Symbol.

then in places like [is_symbol()](https://github.com/jasonwilliams/boa/blob/master/boa/src/builtins/value/mod.rs#L109-L115) just match on Object then check the objectKind. We do something similar, example here:
https://github.com/jasonwilliams/boa/blob/master/boa/src/builtins/value/mod.rs#L731-L781

An example of creating an instance object, take a look at Boolean:
https://github.com/jasonwilliams/boa/blob/master/boa/src/builtins/boolean/mod.rs#L26-L38

**Spec**
https://tc39.es/ecma262/#sec-symbol-objects

**Debugging**
https://github.com/jasonwilliams/boa/blob/master/docs/debugging.md

**Comment by HalidOdat** [comment]
> Symbol is currently a native type on [ValueData](https://github.com/jasonwilliams/boa/blob/master/boa/src/builtins/value/mod.rs#L40-L60) [](/jasonwilliams/boa/blob/HEAD@{2020-05-02T16:21:08Z}/boa/src/builtins/value/mod.rs#L40-L60)
>
> It doesn't need to be, it can be an Object with it's kind set to Symbol.

Isn't it more performant to separate it?

**Comment by Razican** [comment]
> Isn't it more performant to separate it?

It could be, yes, but then, it might make sense to also specialize Arrays, Strings and other type of objects. I'm not against it, since it could allow us to probably use other kind of Rust inner types, but maybe there should be an `Object` enum?

**Comment by HalidOdat** [comment]
> It could be, yes, but then, it might make sense to also specialize Arrays, Strings and other type of objects. I'm not against it, since it could allow us to probably use other kind of Rust inner types, but maybe there should be an `Object` enum?

In v8 they specialize the type like `String` for primitive and `StringObject` for string `Object`.
This helps speed up things since we don't have to look in an internal slot for the data, instead we check the native Rust `String` type.
And so on for the other types.

**Comment by Razican** [comment]
That would be a great addition. Still, I do think that `Symbol` is a type o object and not a different type of JS value. So maybe the `Object` enum makes sense.

**Comment by HalidOdat** [comment]
> That would be a great addition. Still, I do think that `Symbol` is a type o object and not a different type of JS value. So maybe the `Object` enum makes sense.

Yeah that does make sence.
We could have an enum `Object` with `String`, `Array`, `Boolean`, etc, and a `Ordinary` or something like that, that can store objects like `{name: "", age: ""}` and in `ValueData` we have a field of type `Object` enum, and Rusts zero cost abstraction should make it as if it was inlined.

**Comment by jasonwilliams** [comment]
hmm looking back at the spec it does seem like its a primitive.  Does it need a whole object as a backing store?

**Comment by jasonwilliams** [comment]
I’m going to close this for now as we should probably look at the object enum instead. The native symbol seems fine.
