### ISSUE TITLE
Implement for loop execution

### ISSUE THREAD

**Issue by Razican** [jasonwilliams/boa#365]
The parser generates [`Node::ForLoop`][for_node] when it encounters a for loop, but this is not implemented in the executor, so it panics.

This can be implemented by adding another match arm to the [`run()`][exec_run] function in the `exec/mod.rs` file.

[for_node]: https://github.com/jasonwilliams/boa/blob/master/boa/src/syntax/ast/node.rs#L236-L252
[exec_run]: https://github.com/jasonwilliams/boa/blob/master/boa/src/exec/mod.rs#L73-L576

**Comment by akryvomaz** [comment]
Hi, I would like to implement it

**Comment by Razican** [comment]
> Hi, I'd like to implement it

Sure! Let us know if you need any mentoring :)
