### ISSUE TITLE
UnexpectedKeyword(Else)

### ISSUE THREAD

**Issue by caracal7** [jasonwilliams/boa#38]
test.js
```
const fib = n => {
  if(n <= 1) {
    return n;
  } else {
    return fib(n - 1) + fib(n - 2);
  }
}

console.log(fib(10));


let a = "hello world";
a;

```
result
```
Hello
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnexpectedKeyword(Else)', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by jasonwilliams** [comment]
thanks for finding this @caracal7, the output of tokens looks fine https://gist.github.com/jasonwilliams/670694d81dd2d35c13ea00d1ed2eac44

So im guessing the problem is with the parser somewhere:
https://github.com/jasonwilliams/boa/blob/master/src/lib/syntax/parser.rs#L149-L168

Will take a look
