### ISSUE TITLE
`NaN` is lexed as identifier, not as a number

### ISSUE THREAD

**Issue by hello2dj** [jasonwilliams/boa#393]
**Describe the bug**
When lexing `NaN`, we don't get a number, we get an identifier.

**To Reproduce**
Run this JavaScript with `cargo run -- -t {file}.js`:
```javascript
let a = NaN;
```

**Expected behavior**
The token for `NaN` should be :
```
Token {
    kind: NumericLiteral(
        Rational(NaN),
    ),
    pos: Position {
        column_number: 9,
        line_number: 1,
    },
},
```

Instead, we are getting:
```
Token {
    kind: Identifier(
        "NaN",
    ),
    pos: Position {
        column_number: 9,
        line_number: 1,
    },
},
```

This is controlled in https://github.com/jasonwilliams/boa/blob/master/boa/src/syntax/lexer/mod.rs#L591-L602. Appart from checking for `true`, `false` and `null`, we should also check for `NaN` and assign the correct rational, containing `f64::NaN`.

**Comment by Razican** [comment]
There are two issues related to this. First, #359 makes any call to `typeof` panic. But since that's being tracked there, this should track the fact that `NaN` is not lexed as a number, it's lexed as an identifier.

**Comment by Razican** [comment]
I updated the description, so that it's easy to reproduce and fix :)
