### ISSUE TITLE
Test comments in lexer.rs

### ISSUE THREAD

**Issue by jasonwilliams** [jasonwilliams/boa#47]
lexer.rs now has a [test suite](https://github.com/jasonwilliams/boa/blob/master/src/lib/syntax/lexer.rs#L570-L931), but testing comments are still missing.

Test would ensure single-line and multi-line comments are skipped passed and don't generate any tokens

### Contributing
https://github.com/jasonwilliams/boa/blob/master/CONTRIBUTING.md

**Comment by akshay5995** [comment]
@jasonwilliams I'll take this up :)

**Comment by jasonwilliams** [comment]
@akshay5995 you still interested in taking this?

**Comment by Emanon42** [comment]
I am interested in this. Can I take a try?

**Comment by Emanon42** [comment]
#134

**Comment by Emanon42** [comment]
CI failed. I read the [lexer code](https://github.com/jasonwilliams/boa/blob/5df34762e64558c9c1042219ce1baee05777bf1d/src/lib/syntax/lexer.rs#L446-L472) and find out that it actually produces a comment token object which contains the comment string. But you said "single-line and multi-line comments are skipped passed and don't generate any tokens", is that a bug or feature?

**Comment by jasonwilliams** [comment]
its a feature, we don't need to generate tokens for comments, they should be ignored.

**Comment by jasonwilliams** [comment]
if CI fails you can run whatever it does locally
```
cargo fmt --all -- --check
```
is what failed

**Comment by Emanon42** [comment]
#134 has been fixed.
