### ISSUE TITLE
Add test262 as a git submodule

### ISSUE THREAD

**Issue by jasonwilliams** [jasonwilliams/boa#49]
Bring in [test262](https://github.com/tc39/test262) as a submodule. 
Add into the tests directory

**Comment by GalAster** [comment]
I don't think it is necessary

1. It's very huge (40.96 MB), which puts a burden on the CI system.

2. It's useless before implementation assert and module system

We can write a bash script that executes part of the test262 project from the packaged binary executable.

**Comment by leobalter** [comment]
As I suggested in a DM. I recommend doing a shallow checkout of the master branch of Test262 in the CI / Testing processes. I don't think it's necessary to rely on any specific revision of Test262 as it maintains a single track versioning, the master branch. The tests can be filtered out in execution using their flags for features or paths for matching folders.

**Comment by leobalter** [comment]
You can also use test262-harness for the test execution as it already features these options for filtering. We do that running tests for Moddable XS. You'd only need to extend eshost to include a matching agent file.

Pinging @rwaldron for perhaps some eshost/agent info.

**Comment by rwaldron** [comment]
> You'd only need to extend eshost to include a matching agent file.
> Pinging @rwaldron for perhaps some eshost/agent info.

This is something that I can help with. I will try to set aside time today/this week to implement an agent in eshost
