### ISSUE TITLE
Bring Clippy warnings down to 0

### ISSUE THREAD

**Issue by jasonwilliams** [jasonwilliams/boa#61]
There's some low hanging fruit in this one, we've now enabled [Clippy](https://github.com/rust-lang/rust-clippy). Clippy is the Rust linter

This means there's some linting issues that will need fixing. You can see the warnings from each build for e.g here: https://travis-ci.com/jasonwilliams/boa/jobs/213821772

- Install Clippy (link above)
- Checkout the project as normal, and run `cargo clippy` in the project.

**Comment by Korpen** [comment]
I'd like to work on this if it's still needed.

**Comment by jasonwilliams** [comment]
@Korpen sure, assigned

**Comment by jasonwilliams** [comment]
Fixed, thanks @Korpen
