### ISSUE TITLE
warning: unused manifest key: package.edition

### ISSUE THREAD

**Issue by rwaldron** [jasonwilliams/boa#66]
Followed the instructions in the README.md and CONTRIBUTING.md, this is what I ran into: 

```
$ cargo build --verbose
warning: unused manifest key: package.edition
error: failed to parse lock file at: /Users/rwaldron/clonez/boa/Cargo.lock

Caused by:
  expected a section for the key `root`
```

Any tips?

**Comment by Razican** [comment]
What is your Rust version? Latest Rust versions should understand the edition key.

**Comment by rwaldron** [comment]
Ah, thank you—I forgot to `rustup default stable` after updating `rustup` (it's been a while since I worked on a rust project).
