### ISSUE TITLE
implement getOwnProperty for objects

### ISSUE THREAD

**Issue by jasonwilliams** [jasonwilliams/boa#71]
Currently property access to objects is done directly by calling `.properties` you can see here:
https://github.com/jasonwilliams/boa/blob/master/src/lib/js/value.rs#L216

We should define the method `getOwnProperty` for objectData here:
https://github.com/jasonwilliams/boa/blob/master/src/lib/js/object.rs#L16-L27
It might be worth implementing the function `ordinarygetownproperty` first in the same file.

**Spec**
https://tc39.es/ecma262/#sec-ordinarygetownproperty

**Comment by KrisChambers** [comment]
I will take a look at this one too after issue #72 if that is alright.

**Comment by jasonwilliams** [comment]
this is done
