### ISSUE TITLE
add Property::isPropertyKey static method

### ISSUE THREAD

**Issue by jasonwilliams** [jasonwilliams/boa#72]
https://tc39.es/ecma262/#sec-ispropertykey may need to be implemented in the same (object.rs) file also, as that's where the current Property implementation is.

Property struct lives here:
https://github.com/jasonwilliams/boa/blob/master/src/lib/js/object.rs#L53-L66

The argument would be a [JSValue](https://github.com/jasonwilliams/boa/blob/master/src/lib/js/value.rs#L18)

We currently don't support Symbols, so for now you could just test for String.
Or even make use of: https://github.com/jasonwilliams/boa/blob/master/src/lib/js/value.rs#L123-L128

This method will later be used by https://github.com/jasonwilliams/boa/issues/71

**Comment by KrisChambers** [comment]
I will take a look at this.

**Comment by KrisChambers** [comment]
Is it ok to add test modules for some unit tests to the bottom of files? I have noticed that a lot of the modules don't seem to have unit tests. And from some digging it seems a lot of the testing is being done through changing the test.js file and running cargo run. Unless I am missing something and we are putting tests somewhere else.

Also, I noticed there is a task for fixing clippy errors. Do you want this done in 1 go? Or is it ok if I put some clippy fixes for a file I am working on into the Pull Request?

**Comment by jasonwilliams** [comment]
- Yes, it would be great if you could put tests at the bottom of the files
- This somewhat still needs work, an easy way to test the process from start to finish is to run it against some JS files, thats where the test262 work comes in. For now its been very manual. These are not unit tests though.
- We will hopefully merge all the clippy errors issues today
