### ISSUE TITLE
Feature Request: Boa Shell

### ISSUE THREAD

**Issue by rwaldron** [jasonwilliams/boa#74]
Similar to SpiderMonkey's `jsshell`, or V8's `d8`, this is needed to create an `eshost` agent.

`./target/debug/bin` is almost that, but needs: 

1. output written to stdout
    1. only outputs the result of the last evaluation.
1. errors written to stderr

Things needed in the shell runtime itself: 

1. `print()` function in the global scope (or similar). SpiderMonkey's JavaScript shell defines this as: 
    > Evaluates the expression(s) and displays the result(s) on `stdout`, separated by spaces (" ") and terminated by a newline ("\n").
1. `globalThis` or similar mechanism
1. Some way to create a new realm and global object, eg. jsshell's `newGlobal()` or d8's `Realm.global(realmId)` (which requires some way of making a `realmId`, ie. `Realm.create()` or `Realm.createAllowCrossRealmAccess()`)
1. Some way to evaluate a string of source code, eg. jsshell's `evaluate(code)` or d8's `Realm.eval(realmId, code)`

**Comment by jasonwilliams** [comment]
Thanks @rwaldron im sure we can get onto this.

**Comment by jasonwilliams** [comment]
@rwaldron what would happen if you pass an object to print(), would it call `toString()` on that object?

**Comment by jasonwilliams** [comment]
> Some way to create a new realm and global object, eg. jsshell's newGlobal() or d8's Realm.global(realmId) (which requires some way of making a realmId, ie. Realm.create() or Realm.createAllowCrossRealmAccess())

@rwaldron do you have an example of Test262 using this somewhere so we can see for context?

**Comment by Razican** [comment]
I think that something that might be missing here is the ability to create multiline blocks in the shell, if we want to complete it further. But for the rest, this is mostly done, right?

**Comment by HalidOdat** [comment]
> I think that something that might be missing here is the ability to create multiline blocks in the shell, if we want to complete it further. But for the rest, this is mostly done, right?

We have pretty much implemented all of the feature shell request.

Maybe we should close this issue in favor of the new issue #341

**Comment by jasonwilliams** [comment]
I’m happy to close this alao
