### ISSUE TITLE
implement exponentiation operator

### ISSUE THREAD

**Issue by arbroween** [jasonwilliams/boa#89]
The javascript built-in exponentiation operator (`**`) is missing in the implementation of the lexer. It is a shorthand for `Math.pow()` built-in.

It should probably be added to the lexer in this method, somewhere in the big match statement https://github.com/jasonwilliams/boa/blob/master/src/lib/syntax/lexer.rs#L207-L533

The operator's syntax and semantics is defined in this section here https://tc39.es/ecma262/#sec-exp-operator in the spec and does the same thing at runtime than `Math.pow()`, which is already implemented here https://github.com/jasonwilliams/boa/blob/master/src/lib/js/math.rs#L140-L148.

**Comment by arbroween** [comment]
This issue could maybe also be labelled as `good first issue`

**Comment by cpyle0819** [comment]
Re: 'somewhere in the big match statement'. There's already a `*` operator, so `**` should probably be nested within that similar to `\\`.

The `*` match is here: https://github.com/jasonwilliams/boa/blob/master/src/lib/syntax/lexer.rs#L479

**Comment by cpyle0819** [comment]
Now that I look at it, this looks done.

**Comment by oll3** [comment]
The `**` should also be added as an assign op (`**=`)

**Comment by simonbrahan** [comment]
Mind if I take a look at this one?
